#   ____          _                      _     _ _
#  / ___|   _ ___| |_ ___  _ __ ___  ___| |   (_) |__
# | |  | | | / __| __/ _ \| '_ ` _ \/ __| |   | | '_ \
# | |__| |_| \__ \ || (_) | | | | | \__ \ |___| | |_) |
#  \____\__,_|___/\__\___/|_| |_| |_|___/_____|_|_.__/
#
# VK: https://vk.me/dan.owner
# GITHUB: https://github.com/kinseyy
# DISCORD: ENDER#4335
key:
bStats: true # Stats about server
messages: # msg's
  reload: "&aPlugin config reloaded." # arg: reload
  unknown: "&cUnknown command, try /customplaceholder reload." # error not found
placeholders: # CustomLib
  example: "My server is good." # placeholder: %clib_example%
  test: "%vault_eco_balace% - Your balance"
